# Generated by Django 4.2.3 on 2023-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_studentteacher_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', through='school.StudentTeacher', to='school.teacher', verbose_name='Учителя'),
        ),
    ]
